# Generated by Django 3.2 on 2022-10-30 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('gender', models.TextField()),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=100)),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('zipcode', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_email_address', models.EmailField(max_length=500)),
                ('contact_mobile_number', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('first_donation_date', models.DateField(null=True)),
                ('last_donation_date', models.DateField(null=True)),
                ('number_of_donations', models.IntegerField(default=0)),
                ('blood_donated_in_cc', models.IntegerField(default=0)),
                ('last_donation_type', models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Red Cells', 'Red Cells'), ('Platelets', 'Platelets'), ('Plasma', 'Plasma')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
