# Generated by Django 3.2 on 2022-11-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='area',
            field=models.TextField(null=True),
        ),
    ]
