# Generated by Django 3.2 on 2022-10-30 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('request_date_time', models.DateTimeField(auto_now_add=True)),
                ('request_description', models.TextField()),
                ('donation_type_needed', models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Red Cells', 'Red Cells'), ('Platelets', 'Platelets'), ('Plasma', 'Plasma')], max_length=100)),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=100)),
                ('quantity_needed', models.BigIntegerField(default=0)),
                ('donation_uses', models.TextField()),
                ('approx_time_for_donating', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('zipcode', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_email_address', models.EmailField(max_length=500)),
                ('contact_mobile_number', models.TextField()),
                ('website_url', models.URLField(max_length=500)),
                ('logo', models.ImageField(upload_to='images/')),
                ('clinic_establishment_certificate', models.FileField(upload_to='certs/')),
                ('companies_registration_act_certificate', models.FileField(upload_to='certs/')),
                ('societies_registration_act_certificate', models.FileField(upload_to='certs/')),
                ('bloodbank_operating_license_certificate', models.FileField(upload_to='certs/')),
                ('certificate_of_accreditation', models.FileField(upload_to='certs/')),
                ('is_hospital_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequestDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Donated', 'Donated')], default='Requested', max_length=100)),
                ('donor_accepted_date_time', models.DateTimeField()),
                ('donation_date_time', models.DateTimeField()),
                ('collected_quantity_in_cc', models.BigIntegerField()),
                ('transaction_id', models.TextField()),
                ('blood_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.bloodrequest')),
                ('donor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.donorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequestBloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Donated', 'Donated')], default='Requested', max_length=100)),
                ('blood_bank_accepted_date_time', models.DateTimeField()),
                ('donation_date_time', models.DateTimeField()),
                ('collected_quantity_in_cc', models.BigIntegerField()),
                ('transaction_id', models.TextField()),
                ('blood_bank_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_banks.bloodbankprofile')),
                ('blood_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.bloodrequest')),
            ],
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.hospitalprofile'),
        ),
    ]
