# Generated by Django 3.2 on 2022-10-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestbloodbank',
            name='blood_bank_accepted_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestbloodbank',
            name='collected_quantity_in_cc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestbloodbank',
            name='donation_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestbloodbank',
            name='transaction_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestdonor',
            name='collected_quantity_in_cc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestdonor',
            name='donation_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestdonor',
            name='donor_accepted_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestdonor',
            name='transaction_id',
            field=models.TextField(null=True),
        ),
    ]
