# Generated by Django 3.2 on 2022-10-30 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_bank_name', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('zipcode', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_email_address', models.EmailField(max_length=500)),
                ('contact_mobile_number', models.TextField()),
                ('website_url', models.URLField(max_length=500)),
                ('logo', models.ImageField(upload_to='images/')),
                ('bloodbank_operating_license_certificate', models.FileField(upload_to='certs/')),
                ('certificate_of_accreditation', models.FileField(upload_to='certs/')),
                ('is_blood_bank_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('camp_description', models.TextField()),
                ('camp_date', models.DateField()),
                ('camp_time', models.TimeField()),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('zipcode', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_email_address', models.EmailField(max_length=500)),
                ('contact_mobile_number', models.TextField()),
                ('team_size', models.IntegerField()),
                ('camp_brochure', models.FileField(upload_to='camps/')),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_banks.bloodbankprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodCampEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('camp_enrollment_status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Donated', 'Donated')], max_length=100)),
                ('enrolled_date_time', models.DateTimeField(auto_now_add=True)),
                ('donation_date_time', models.DateTimeField()),
                ('blood_group_collected', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=100)),
                ('collected_quantity_in_cc', models.BigIntegerField()),
                ('transaction_id', models.TextField()),
                ('blood_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_banks.bloodcamp')),
                ('donor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodBankInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_plus_in_cc', models.BigIntegerField()),
                ('a_minus_in_cc', models.BigIntegerField()),
                ('b_plus_in_cc', models.BigIntegerField()),
                ('b_minus_in_cc', models.BigIntegerField()),
                ('o_plus_in_cc', models.BigIntegerField()),
                ('o_minus_in_cc', models.BigIntegerField()),
                ('ab_plus_in_cc', models.BigIntegerField()),
                ('ab_minus_in_cc', models.BigIntegerField()),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood_banks.bloodbankprofile')),
            ],
        ),
    ]
