# Generated by Django 3.2 on 2022-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_banks', '0003_bloodbankprofile_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcamp',
            name='area',
            field=models.TextField(null=True),
        ),
    ]
